export const DEFAULT_SCHEDULE_GROUPS = [
  { name: "Weekday", hebrewName: "חול", color: "#4CAF50" },
  { name: "Shabbat", hebrewName: "שבת", color: "#2196F3" },
  { name: "Rosh Hashana", hebrewName: "ראש השנה", color: "#FF9800" },
  { name: "Tzom Gedaliah", hebrewName: "צום גדליה", color: "#795548" },
  { name: "Yom Kippur", hebrewName: "יום כיפור", color: "#F5F5F5" },
  { name: "Sukkot", hebrewName: "סוכות", color: "#8BC34A" },
  { name: "Hoshana Rabba", hebrewName: "הושענא רבה", color: "#689F38" },
  { name: "Shmini Atzeret", hebrewName: "שמיני עצרת", color: "#4CAF50" },
  { name: "Simchat Torah", hebrewName: "שמחת תורה", color: "#66BB6A" },
  { name: "Chanukah", hebrewName: "חנוכה", color: "#FFC107" },
  { name: "Asara B'Tevet", hebrewName: "עשרה בטבת", color: "#795548" },
  { name: "Tu B'Shvat", hebrewName: "ט״ו בשבט", color: "#4CAF50" },
  { name: "Taanit Esther", hebrewName: "תענית אסתר", color: "#795548" },
  { name: "Purim", hebrewName: "פורים", color: "#E91E63" },
  { name: "Shushan Purim", hebrewName: "שושן פורים", color: "#EC407A" },
  { name: "Pesach", hebrewName: "פסח", color: "#FF5722" },
  { name: "Chol HaMoed Pesach", hebrewName: "חול המועד פסח", color: "#FF7043" },
  { name: "Shvi'i Shel Pesach", hebrewName: "שביעי של פסח", color: "#FF5722" },
  { name: "Yom HaShoah", hebrewName: "יום השואה", color: "#424242" },
  { name: "Yom HaZikaron", hebrewName: "יום הזיכרון", color: "#546E7A" },
  { name: "Yom HaAtzmaut", hebrewName: "יום העצמאות", color: "#1565C0" },
  { name: "Lag BaOmer", hebrewName: "ל״ג בעומר", color: "#FF6F00" },
  { name: "Yom Yerushalayim", hebrewName: "יום ירושלים", color: "#FFD54F" },
  { name: "Shavuot", hebrewName: "שבועות", color: "#43A047" },
  { name: "Shiva Asar B'Tamuz", hebrewName: "שבעה עשר בתמוז", color: "#795548" },
  { name: "Tisha B'Av", hebrewName: "תשעה באב", color: "#3E2723" },
  { name: "Tu B'Av", hebrewName: "ט״ו באב", color: "#E91E63" },
  { name: "Erev Shabbat", hebrewName: "ערב שבת", color: "#1E88E5" },
  { name: "Erev Yom Tov", hebrewName: "ערב יום טוב", color: "#FB8C00" },
  { name: "Rosh Chodesh", hebrewName: "ראש חודש", color: "#AB47BC" },
  { name: "Chol HaMoed Sukkot", hebrewName: "חול המועד סוכות", color: "#9CCC65" },
  { name: "Sefirat HaOmer", hebrewName: "ספירת העומר", color: "#7E57C2" },
  { name: "Bein HaMetzarim", hebrewName: "בין המצרים", color: "#6D4C41" },
  { name: "Elul", hebrewName: "אלול", color: "#5C6BC0" },
  { name: "Aseret Yemei Teshuva", hebrewName: "עשרת ימי תשובה", color: "#EF5350" },
] as const;
