import { writeFileSync } from "node:fs";
import { ENV_SPEC } from "../lib/env-spec";

const lines = [
  "# Generated by `npm run gen:env-example` from lib/env-spec.ts. Do not edit by hand.",
  "",
  ...ENV_SPEC.flatMap((entry) => [
    `# ${entry.description}`,
    `${entry.key}="${entry.example}"`,
    "",
  ]),
];

writeFileSync(".env.example", lines.join("\n"), "utf8");
console.log("gen-env-example: wrote .env.example");
